version: "3.9"

services:
  salary-service:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_HOST=your_db_host
      - DB_PORT=your_db_port
      - DB_NAME=your_db_name
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_postgres_db
